const mockProducts = [
    {
      _id: "1",
      nombre: "Producto 1",
      marca: "Marca A",
      precio: 50000,
      descuento: 0.2,
      calificacion: 4.5,
      imagenes: ["image1.jpg"],
      patrocinado: true,
      envioGratis: true,
    },
    {
      _id: "2",
      nombre: "Producto 2",
      marca: "Marca B",
      precio: 30000,
      descuento: 0.1,
      calificacion: 4.0,
      imagenes: ["image2.jpg"],
      patrocinado: false,
      envioGratis: false,
    },
    {
      _id: "3",
      nombre: "Producto 3",
      marca: "Marca C",
      precio: 70000,
      descuento: 0.3,
      calificacion: 5.0,
      imagenes: ["image3.jpg"],
      patrocinado: false,
      envioGratis: true,
    },
    {
      _id: "4",
      nombre: "Producto 4",
      marca: "Marca D",
      precio: 40000,
      descuento: 0.15,
      calificacion: 3.5,
      imagenes: ["image4.jpg"],
      patrocinado: true,
      envioGratis: false,
    },
    {
        _id: "5",
        nombre: "Producto 4",
        marca: "Marca D",
        precio: 40000,
        descuento: 0.15,
        calificacion: 3.5,
        imagenes: ["image4.jpg"],
        patrocinado: true,
        envioGratis: false,
      },
      {
        _id: "6",
        nombre: "Producto 4",
        marca: "Marca D",
        precio: 40000,
        descuento: 0.15,
        calificacion: 3.5,
        imagenes: ["image4.jpg"],
        patrocinado: true,
        envioGratis: false,
      },
  ];
  
  export default mockProducts;
  